# Generated by Django 4.2 on 2024-05-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank='True', null='True', upload_to='user_pictures/', verbose_name='аватар'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank='True', max_length=100, null='True', verbose_name='страна'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank='True', max_length=35, null='True', verbose_name='телефон'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank='True', max_length=10, null='True', verbose_name='код верификации'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='почта'),
        ),
    ]
