# Generated by Django 4.2 on 2024-06-04 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('content', models.TextField(blank='True', null='True', verbose_name='содержимое статьи')),
                ('preview', models.ImageField(blank='True', null='True', upload_to='blogpost_images/', verbose_name='изображение')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ('created_at',),
            },
        ),
    ]
