# Generated by Django 4.2 on 2024-05-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank='True', max_length=100, null='True', verbose_name='Ф. И. О.'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank='True', null='True', verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='контактный email'),
        ),
    ]
