# Generated by Django 4.2 on 2024-05-26 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_client_name_alter_client_comment_alter_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity', models.CharField(choices=[('day', 'раз в день'), ('week', 'раз в неделю'), ('month', 'раз в месяц')], default='разовая', max_length=50, verbose_name='периодичность')),
                ('status', models.CharField(blank='True', choices=[('completed', 'Завершена'), ('created', 'Создана'), ('launched', 'Запущена')], max_length=50, null='True', verbose_name='статус рассылки')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начала')),
                ('next_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='следующая дата')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='конечная дата')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='актуальная')),
                ('client', models.ManyToManyField(to='main.client', verbose_name='клиенты')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='сообщение')),
                ('owner', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('start_date',),
            },
        ),
    ]
