# Generated by Django 4.2 on 2024-05-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mailing_time', models.DateTimeField(auto_now=True, null='True', verbose_name='время последней попытки')),
                ('status', models.BooleanField(default=False, verbose_name='статус попытки рассылки')),
                ('response', models.CharField(blank='True', max_length=255, null='True', verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='main.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ('last_mailing_time',),
            },
        ),
    ]
