# Generated by Django 4.2 on 2024-05-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='статус попытки рассылки'),
        ),
    ]
