# Generated by Django 4.2 on 2024-06-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_logs_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('start_date',), 'permissions': [('set_is_activated', 'может менять активность рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
